apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-grafana
  namespace: hackathon
  labels:
    app: hackathon
    component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon
      component: grafana
  template:
    metadata:
      labels:
        app: hackathon
        component: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-storage
